### ISSUE TITLE
Append To Csv File giving "IndexError: list index out of range"

### ISSUE THREAD

**Issue by akashyap1** [s4int/robotframework-CSVLibrary#12]
Empty Csv File    ${outputFile}    
   @{list}=    Read Csv File To List    ${inputFile}   
    @{list}=    Change dateField for the csv data    ${list}    ${stlDate}    ${dataSource}
    Append To Csv File    ${outputFile}    ${list}

${inputFile}  --> It is a CSV file containing the data
${outputFile} --> Created a empty csv file

The above code was working file with Python 2.7 and RF 3.1.2 with the version 0.0.3

But after upgrading the Python to 3.8, started getting the error ""IndexError: list index out of range"
 for the keyword Append To Csv File

Please help on this.

**Comment by akashyap1** [comment]
I think I got the error, there is a change in the code.
The earlier version of the library is having the function like
    def append_to_csv_file(self, filename, data, **kwargs):
        """This keyword will append data to a new or existing CSV file.
        
        - ``filename``:  name of csv file
        - ``data``: iterable(e.g. list or tuple) data.
        - ``quoting`` (int):
          _0_: QUOTE_MINIMAL
          _1_: QUOTE_ALL
          _2_: QUOTE_NONNUMERIC
          _3_: QUOTE_NONE
        """
        if isinstance(data[0], dict):
            data = map(lambda row: row.items(), data)
        self._open_csv_file_for_write(filename, data=data, csv_writer=csv.writer, **kwargs)


The new version has changes and it is like 

    def append_to_csv_file(self, filename, data, **kwargs):
        """This keyword will append data to a new or existing CSV file.

        - ``filename``:  name of csv file
        - ``data``: iterable(e.g. list or tuple) data.
        - ``quoting`` (int):
          _0_: QUOTE_MINIMAL
          _1_: QUOTE_ALL
          _2_: QUOTE_NONNUMERIC
          _3_: QUOTE_NONE
        """

        if isinstance(data, dict):
            data = [data]

        print(data)

        fieldnames = self._open_csv_file_for_read(
            filename,
            csv_reader=csv.reader,
            line_numbers=[0],
            **kwargs
        )[0]

        self._open_csv_file_for_write(
            filename,
            data=data,
            csv_writer=csv.DictWriter,
            fieldnames=fieldnames,
            **kwargs
        )

The error comes due the code with the line ----    line_numbers=[0].

Please check at your end.

**Comment by s4int** [comment]
Thank you for that. I will check it.

**Comment by akashyap1** [comment]
May I know by when you will fix it.

**Comment by s4int** [comment]
Please check changes on branch AppendToCsvFile, and let me know if it fixes issue for you.

**Comment by akashyap1** [comment]
The issue is still not fixed.

I tried to run directly in the file by creating the object using below code in the end:
csvT = CSVLibrary()
csvT.empty_csv_file(os.path.abspath("C:/TestSuites/resource/csvTest.csv"))
list= csvT.read_csv_file_to_list(os.path.abspath("C:/TestSuites/resource/test.csv"))
csvT.append_to_csv_file(os.path.abspath("C:/TestSuites/resource/csvTest.csv"),list)

Log traces:
Traceback (most recent call last):
  File "C:/TestSuites/test/csvTest.py", line 276, in <module>
    csvT.append_to_csv_file(os.path.abspath("C:/TestSuites/resource/csvTest.csv"),list)
  File "C:/TestSuites/test/csvTest.py", line 169, in append_to_csv_file
    header = self._open_csv_file_for_read(
  File "C:/TestSuites/test/csvTest.py", line 42, in _open_csv_file_for_read
    return self._read_csv(csv_handler, csv_reader, line_numbers, **kwargs)
  File "C:/TestSuites/test/csvTest.py", line 35, in _read_csv
    if line_numbers is not None and isinstance(line_numbers, list):
TypeError: isinstance() arg 2 must be a type or tuple of types

**Comment by s4int** [comment]
@akashyap1 please provide full robot test including test data. It will be easier for me to reproduce the issue.

**Comment by akashyap1** [comment]
@s4int , please create a csv file with the following data as could not see teh option of attaching the file here:
=======================DATA To create a csv file======================
t,s,d,r,t,y,g,h,j,kl,k,k,k,k,h,y,f,d,k,k,k,k,g,f,r,e,d,w,h,h,s,n,i
22012116071,DBU,126344598,DBU,VOL,OTC,Equity.HSBA.L.1516656,540528,GB0005405286,HSBA.L,HSBA LN,GBP,21/01/2022,21/01/2022,"-4,000,000.00",-750,"-4,000,000.00",0,DFP,PENDING,SETT//PEND,MTCH//MACH,,,AWAITING SHARES FROM COUNTERPARTY,Unreleased,"Dec 16, 2021 12:40:58 AM",GB,Sell,AGENT-CITIGB2L,6080065447,SHUNT_FEE,SEC_RECEIPT
22012116072,DBU,126344598,DBU,GDRH,,Equity.AEMN.SI.93549,6563875,SG1M77906915,AEMN.SI,AREIT SP,SGD,21/01/2022,21/01/2022,"3,320,000.00",0,"3,320,000.00",0,DFP,VERIFIED,,MTCH//MACH,,,AWAITINGNEXTSETTLEMENTCYCLE,Matched,"Dec 17, 2021 9:15:40 AM",SG,Buy,AGENT-CITISGSG,814333248,PRINCIPAL,SEC_RECEIPT
22012116073,DBU,126344598,DBU,GDRH,,Equity.CMLT.SI.409950,6420129,SG1M51904654,CMLT.SI,CICT SP,SGD,21/01/2022,21/01/2022,"-6,000,000.00",0,"-6,000,000.00",0,DFP,CREATED,SETT//PEND,,,,CPTY IS SHORT OF STOCK,Unreleased,"Dec 17, 2021 9:15:40 AM",SG,Sell,AGENT-CITISGSG,814333248,PRINCIPAL,SEC_RECEIPT
22012116074,DBU,126344598,DBU,GDRH,,Equity.CAPN.SI.61402131,BNHXFJ6,SGXE62145532,CAPN.SI,CLI SP,SGD,21/01/2022,21/01/2022,"4,000,000.00",0,"4,000,000.00",0,DFP,SETTLED,SETT//PEND,,,,TRADE NOT RECOGNISED BY CPTY,Settled,"Dec 17, 2021 9:15:40 AM",SG,Buy,AGENT-CITISGSG,814333248,PRINCIPAL,SEC_RECEIPT
=======================DATA To create a csv file======================

Use the below code to execute, it is nothing the same file _init_.py of csv library to execute.
csvT = CSVLibrary()
csvT.empty_csv_file(os.path.abspath("C:/TestSuites/resource/csvTest.csv"))
list= csvT.read_csv_file_to_list(os.path.abspath("C:/TestSuites/resource/test.csv"))
csvT.append_to_csv_file(os.path.abspath("C:/TestSuites/resource/csvTest.csv"),list)

I hope this will help.

**Comment by s4int** [comment]
Above test works for me without issues on branch [AppendToCsvFile](https://github.com/s4int/robotframework-CSVLibrary/tree/AppendToCsvFile).

I believe above test is similar to the one added by me:
https://github.com/s4int/robotframework-CSVLibrary/blob/e458f8430d2e8660f15189c29eb880b01114b281/tests/AppendToCsvFile.robot#L9-L16

Please verify the fix and let me know so I can release new version.

**Comment by akashyap1** [comment]
@s4int , the file is getting created but still there is an issue. You are adding an extra line after each each line

Could you please check at your end? Try to see the csv file from which the data will be copied. I am following the approach of opening the file that has created using the keyword "append to csv file" and compare it with original csv file from where it has copied the data. Please find below the test case.

*** Test Cases ***
TestCSV
    empty csv file  C:/TestSuites/resource/csvTest.csv
    ${listData}=    read csv file to list   C:/TestSuites/resource/test.csv
    log     ${listData}
    append to csv file      C:/TestSuites/resource/csvTest.csv      ${listData}

**Comment by akashyap1** [comment]
@s4int , the file is getting created but still there is an issue. You are adding an extra line after each each line

Could you please check at your end? Try to see the csv file from which the data will be copied. I am following the approach of opening the file that has created using the keyword "append to csv file" and compare it with original csv file from where it has copied the data. Please find below the test case.

*** Test Cases ***
TestCSV
    empty    csv file C:/TestSuites/resource/csvTest.csv
    ${listData}=    read csv file to list C:/TestSuites/resource/test.csv
    log    ${listData}
    append to csv file    C:/TestSuites/resource/csvTest.csv    ${listData}

**Comment by s4int** [comment]
This is how csv package works. It puts empty line at the end of csv file.

```
import csv

dd = [
    (1, "a"),
    (2, "b"),
    (3, "c"),
]

with open('new_file.csv', 'a') as csv_handler:
    writer = csv.writer(csv_handler)
    writer.writerows(dd)
```

new_file.csv:
```
1,a
2,b
3,c

```

As for adding new extra line after each line. There is no such thing in my code. I think it can be related with \r\n on windows.

**Comment by akashyap1** [comment]
But, I think it is something working fine with python 2.7 and no extra line has been added.
In my opinion, we should handle this as well otherwise it looks like some issue in creating a new csv file from the existing csv file.

**Comment by alevi-ibm** [comment]
@s4int I have the very same issue. Here's a snapshot of the flow and the array of arrays.

![image](https://user-images.githubusercontent.com/51128824/151457005-578aa9d5-5e1e-4f44-816c-72e09a8da3c5.png)

The contents of ${csvData.csv} ...

`[['preferred_username', 'family_name', 'given_name', 'name.middleName', 'name', 'displayName', 'job_title', 'work_number', 'fax_number', 'home_number', 'mobile_number', 'pager_number', 'email', 'addresses.locality.work', 'addresses.streetAddress.work', 'addresses.formatted.work', 'addresses.postalCode.work', 'addresses.country.work', 'addresses.region.work', 'addresses.formatted.home', 'preferredLanguage', 'department', 'urn:ietf:params:scim:schemas:extension:ibm:2.0:User:delegate', 'urn:ietf:params:scim:schemas:extension:enterprise:2.0:User:manager.value', 'employee_id', 'urn:ietf:params:scim:schemas:extension:ibm:2.0:User:emailVerified', 'externalId', 'urn:ietf:params:scim:schemas:extension:ibm:2.0:User:accountExpires', 'urn:ietf:params:scim:schemas:extension:ibm:2.0:User:customAttributes.customAttribute1'], ['am5_csv_557BrcK_am5_1_user@cictest.ibm.com', 'familyName', 'givenName', 'middleName', 'formattedName', 'am5_1_user@cictest.ibm.com', 'title', '512-111-1111', '512-111-1111', '512-111-1111', '512-111-1111', '512-111-1111', 'am5_1_user@cictest.ibm.com', 'locality', 'streetAddress', 'postalAddress', '78751', 'US', 'region', 'formatted', 'en-US', 2345, '609000EQH4', '609000EQH4', 777, 123453, 'am5_1_user', '2022-01-28T01:53:55Z', 'customAttribute1']]`

**Comment by akashyap1** [comment]
@alevi-ibm, the issue is fixed and you can refer to the branch [AppendToCsvFile](https://github.com/s4int/robotframework-CSVLibrary/tree/AppendToCsvFile).

But, there is one new issue that it adds an extra line after each line in the newly created csv file.

**Comment by alevi-ibm** [comment]
@s4int Thank you! I'll check it out!

**Comment by s4int** [comment]
@akashyap1 It should be fixed now.

The issue with newlines is specific to Windows and it needs to be handled differently in python 2 and 3.
More details [csv-in-python-adding-an-extra-carriage-return-on-windows](https://stackoverflow.com/questions/3191528/csv-in-python-adding-an-extra-carriage-return-on-windows)

**Comment by akashyap1** [comment]
@s4int , the fix working fine.
Thanks for your support.
