### ISSUE TITLE
CSVLibrary should use Robot Framework DotDict for "read csv file to associative"

### ISSUE THREAD

**Issue by JockeJarre** [s4int/robotframework-CSVLibrary#15]
Currently when using CSVLibrary to load CSV files into a list of dictionaries, it is loading them as the standard python library as OrderedDict's.

To make the result usable as other Dictionaries created by Robot Framework, it would be nice to use the Robot Framework sub classed DotDict class instead.  ( robot.utils.dotdict.DotDict )

With the DotDict class it would be possible to do like this (as long as the header does not contain spaces):

```    
*** Test Cases ***

Read csv file to a dict example test
  @{dict}=    read csv file to associative  data.csv
  Log  ${dict[0].first_name}  ${dict[0].last_name}
```

**Comment by JockeJarre** [comment]
Did some tries...

import csv
from robot.utils.dotdict import DotDict

class DocDictReader(csv.DictReader):
    def __next__(self):
        return DotDict(super().__next__())

I think it should be ok to use it like this?

**Comment by s4int** [comment]
Thank you for pointing this out. I will try to implement that with next version.

**Comment by JockeJarre** [comment]
I hope you do not mind, did a pull request...

**Comment by s4int** [comment]
@JockeJarre Thank You, merged.

**Comment by JockeJarre** [comment]
Will there be a new version?

**Comment by s4int** [comment]
New version published. @JockeJarre Thank You

**Comment by JockeJarre** [comment]
Hello, just FYI, the solution I gave you is for python 3 only... 
I see that your code do things for PY2/3 but maybe it is time to leave Python 2 behind?
