### ISSUE TITLE
Please add a possibility to "read csv file to associative" from variable

### ISSUE THREAD

**Issue by xxxszxxx** [s4int/robotframework-CSVLibrary#3]
Please add a possibility to "read csv file to associative" from variable.
Currently the only option is to read from a csv file. 
It would be nice to load it from a variable too.

**Comment by s4int** [comment]
Done in new release.
Please check: https://github.com/s4int/robotframework-CSVLibrary/blob/master/tests/ReadCSVTest.robot#L33
