### ISSUE TITLE
Please support python3+

### ISSUE THREAD

**Issue by 007bsd** [s4int/robotframework-CSVLibrary#4]
When trying to install csvlibrary with python3 getting below error. It seems it is yet support python3.

```Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/fr/jtjjqpbs1sx0lxh6qbgzgdjw00gftq/T/pip-build-nyn_ua1n/robotframework-csvlibrary/```

Kindly provide the support for python3 as well.

**Comment by gruentee** [comment]
Yes, please!

**Comment by Noordsestern** [comment]
Please review #5
