### ISSUE TITLE
Version 0.0.3 with Python 3 support has not been put on PyPi

### ISSUE THREAD

**Issue by CMTaylor** [s4int/robotframework-CSVLibrary#9]
Please put a universal, Py2 & Py3, build of this on PyPi. https://pypi.org/project/robotframework-csvlibrary/ is still at version 0.0.2

**Comment by IncredibleLou** [comment]
I would like that as well :)

**Comment by kumarkrish85** [comment]
Any update on this issue?

**Comment by HaaiHenkie** [comment]
Workaround:

1. Open the [robotframework-CSVLibrary repository](https://github.com/s4int/robotframework-CSVLibrary)
2.  Click Code -> Download ZIP
![image](https://user-images.githubusercontent.com/8525411/116821128-eae16f80-ab78-11eb-8024-b49cfc65fc14.png)
3. Unzip this file to a temporary directory
4. Open a command prompt (Windows) or terminal (Linux/MacOS)
5. Chang the directory to the temporary directory in step 3
6. Type `python setup.py install`

You have now installed v0.0.3 of robotframework-CSVLibrary.

**Comment by Lua27** [comment]
I would also appreciate 0.0.3 being published

**Comment by s4int** [comment]
Just released version 0.0.3. I've added couple more tests and verified python 2.7 and 3.x.

Sorry for delay :)
It's my fun project.
